Main
geogo-in/pro-kriyam pull request #8
Opened 2023-05-01 09:26 UTC by kanjilal1122

2023-05-02 07:54 UTC, dipanjanpanja6 commented
Please add issue ID in the description or in branch name

2023-05-02 11:40 UTC, dipanjanpanja6 requested changes

2023-05-02 11:40 UTC, dipanjanpanja6 commented on src/pages/projectBacklog/components/SprintIssue.jsx
> +        {/* <MenuItem value="" >
remove this commented code

2023-05-02 11:40 UTC, dipanjanpanja6 commented on src/pages/projectBacklog/components/SprintIssue.jsx
> +        {/* <MenuItem value="" >
format code before push.
https://code.visualstudio.com/docs/editor/codebasics#:~:text=VS%20Code%20has%20great%20support,)%20%2D%20Format%20the%20selected%20text.

2023-05-02 13:48 UTC, kanjilal1122 commented
Remove the commented code .

2023-05-03 03:50 UTC, dipanjanpanja6 approved these changes

2023-05-03 03:50 UTC, merged